version: '3.6'

volumes:
  node_modules_store:

services:
  web:
#    build: .
    image: nginx:latest
    container_name: sample-web-nginx
    volumes:
#      - ./server:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./server:/var/www/html
      - node_modules_store:/usr/share/nginx/html/node_modules
    ports: ["8080:80"]

